import './global.css';

export const metadata = {
	title: 'Welcome to card-game.io',
	description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<meta charSet="utf-8" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
			</head>
			<body className="prose prose-slate">{children}</body>
		</html>
	);
}
